# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_time',)},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='abstract',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='created_date',
            new_name='created_time',
        ),
        migrations.AddField(
            model_name='article',
            name='modified_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
